version: '3.9'

# This file is a placeholder to satisfy linters.
# The real docker-compose content is rendered from docker-compose.yml.j2 by Copier.

services:
  placeholder:
    image: alpine:3.19
    command: ["sh", "-c", "echo 'Rendered from template by Copier; replace after generation.' && sleep 1"]
