# Makefile for common developer tasks

.PHONY: help generate-ignores

help:
	@echo "Available targets:"
	@echo "  generate-ignores  - Regenerate top-level ignore files from .config/filelists/"

# Regenerate ignore files (autogenerated from .config/filelists/)
generate-ignores:
	node bin/generate-ignores.js
