FROM rust:1.98.1 as builder

WORKDIR /usr/src/app
COPY . .
RUN cargo install --path .

FROM debian:trixie-slim
COPY --from=builder /usr/local/cargo/bin/{{ project_slug }} /usr/local/bin/
CMD ["{{ project_slug }}", "--help"]
