import fs from 'fs/promises';
import path from 'path';
import { Command } from 'commander';
import { createLogger } from './logger.js';

/**
 * Completion script version
 * Increment this when completion script format changes
 */
export const COMPLETION_VERSION = '1.0.0';

/**
 * Shell completion types supported
 */
export type ShellType = 'bash' | 'zsh' | 'fish';

/**
 * Completion script generation options
 */
export interface CompletionOptions {
    /**
     * Shell type to generate completion for
     */
    shell: ShellType;
    /**
     * Output directory for completion scripts
     */
    outputDir?: string;
    /**
     * Whether to output to stdout instead of file
     */
    stdout?: boolean;
}

/**
 * Generate shell completion script for the given program
 * @param program - The commander program instance
 * @param options - Completion generation options
 * @returns The completion script content
 */
export function generateCompletionScript(
    program: Command,
    options: CompletionOptions
): string {
    const { shell } = options;

    switch (shell) {
        case 'bash':
            return generateBashCompletion(program);
        case 'zsh':
            return generateZshCompletion(program);
        case 'fish':
            return generateFishCompletion(program);
        default:
            throw new Error(`Unsupported shell type: ${shell}`);
    }
}

/**
 * Generate bash completion script
 * @param program - The commander program instance
 * @returns Bash completion script content
 */
function generateBashCompletion(program: Command): string {
    const programName = program.name();
    return `# Bash completion for ${programName}
# Version: ${COMPLETION_VERSION}
# Generated by ${programName}
_${programName}_completion() {
    local cur prev words cword
    _init_completion || return

    case \$prev in
        --config)
            _filedir
            return
            ;;
        --color)
            COMPREPLY=(\$(compgen -W "auto always never" -- "\$cur"))
            return
            ;;
        *)
            ;;
    esac

    if [[ \$cur == -* ]]; then
        COMPREPLY=(\$(compgen -W "
            --help
            --version
            --quiet
            --verbose
            --debug
            --usage
            --color
            --config
            --json
        " -- "\$cur"))
    fi
}

complete -F _${programName}_completion ${programName}
`;
}

/**
 * Generate zsh completion script
 * @param program - The commander program instance
 * @returns Zsh completion script content
 */
function generateZshCompletion(program: Command): string {
    const programName = program.name();
    return `#compdef ${programName}
# Version: ${COMPLETION_VERSION}
# Generated by ${programName}

_${programName}() {
    local -a commands

    _arguments -C \\
        '--help[Display help for command]' \\
        '--version[Output the version number]' \\
        '--quiet[Suppress all output except errors]' \\
        '--verbose[Enable verbose output with extra details]' \\
        '--debug[Enable debug-level logging]' \\
        '--usage[Display usage information]' \\
        '--color[Color mode: auto, always, or never]:mode:(auto always never)' \\
        '--config[Config file path]:file:_files' \\
        '--json[Output results as JSON]' \\
        '*::args:->args'

    case \$state in
        args)
            _files
            ;;
    esac
}

_${programName}
`;
}

/**
 * Generate fish completion script
 * @param program - The commander program instance
 * @returns Fish completion script content
 */
function generateFishCompletion(program: Command): string {
    const programName = program.name();
    return `# Fish completion for ${programName}
# Version: ${COMPLETION_VERSION}
# Generated by ${programName}

complete -c ${programName} -f

complete -c ${programName} -l help -d 'Display help for command'
complete -c ${programName} -l version -d 'Output the version number'
complete -c ${programName} -l quiet -d 'Suppress all output except errors'
complete -c ${programName} -l verbose -d 'Enable verbose output with extra details'
complete -c ${programName} -l debug -d 'Enable debug-level logging'
complete -c ${programName} -l usage -d 'Display usage information'
complete -c ${programName} -l color -d 'Color mode: auto, always, or never' -x -a 'auto always never'
complete -c ${programName} -l config -d 'Config file path' -r
complete -c ${programName} -l json -d 'Output results as JSON'
`;
}

/**
 * Write completion script to file
 * @param program - The commander program instance
 * @param options - Completion generation options
 * @param logger - Logger instance
 */
export async function writeCompletionScript(
    program: Command,
    options: CompletionOptions,
    logger: ReturnType<typeof createLogger>
): Promise<void> {
    const { shell, outputDir, stdout } = options;
    const script = generateCompletionScript(program, options);

    if (stdout) {
        console.log(script);
        return;
    }

    const outputDirectory = outputDir || path.join(process.cwd(), 'completions');
    const fileName = `${program.name()}.${shell}`;
    const filePath = path.join(outputDirectory, fileName);

    try {
        await fs.mkdir(outputDirectory, { recursive: true });
        await fs.writeFile(filePath, script, 'utf-8');
        logger.info(`Completion script written to: ${filePath}`);
    } catch (error) {
        throw new Error(`Failed to write completion script: ${error}`);
    }
}

/**
 * Get installation instructions for the given shell
 * @param shell - Shell type
 * @param programName - Name of the CLI program
 * @returns Installation instructions
 */
export function getCompletionInstallInstructions(
    shell: ShellType,
    programName: string
): string {
    switch (shell) {
        case 'bash':
            return `# Bash completion installation

# Add to ~/.bashrc or ~/.bash_profile:
source ~/.local/share/bash-completion/completions/${programName}

# Or for system-wide installation:
sudo cp completions/${programName}.bash /usr/share/bash-completion/completions/${programName}
`;
        case 'zsh':
            return `# Zsh completion installation

# Add to ~/.zshrc:
fpath=(~/.local/share/zsh/completions \$fpath)
autoload -U compinit && compinit

# Copy completion file:
mkdir -p ~/.local/share/zsh/completions
cp completions/${programName}.zsh ~/.local/share/zsh/completions/_${programName}
`;
        case 'fish':
            return `# Fish completion installation

# Copy completion file to fish completions directory:
mkdir -p ~/.config/fish/completions
cp completions/${programName}.fish ~/.config/fish/completions/${programName}.fish
`;
        default:
            throw new Error(`Unsupported shell type: ${shell}`);
    }
}

/**
 * Validate completion script syntax
 * @param script - The completion script content
 * @param shell - Shell type
 * @returns Validation result
 */
export function validateCompletionScript(
    script: string,
    shell: ShellType
): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (!script || script.trim().length === 0) {
        errors.push('Script is empty');
    }

    // Basic syntax checks
    if (shell === 'bash') {
        if (!script.includes('complete -F')) {
            errors.push('Missing bash complete function');
        }
    } else if (shell === 'zsh') {
        if (!script.includes('#compdef')) {
            errors.push('Missing zsh compdef directive');
        }
    } else if (shell === 'fish') {
        if (!script.includes('complete -c')) {
            errors.push('Missing fish complete command');
        }
    }

    return {
        valid: errors.length === 0,
        errors,
    };
}
