extra-substituters = http://localnet-artifact-harmonia:5000 http://localnet-artifact-ncps:5001 https://cache.nixos.org
extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
priority = 30 40 100
experimental-features = nix-command flakes
trusted-users = root developer
